language: elixir

dist: trusty
sudo: required

install:
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get
    - mix deps.compile
    - MIX_ENV=test mix compile

script:
    - .travis/script.sh $PRESET

env:
    - PRESET=test

branches:
    only:
        - master

elixir:
    - 1.6
    - 1.7

otp_release:
    - 21.2

matrix:
    include:
        - name: "Dialyzer"
          otp_release: 21.2
          elixir: 1.6.6
          env: PRESET=dialyzer
        - name: "Credo"
          otp_release: 21.2
          elixir: 1.6.6
          env: PRESET=credo
        - name: "Coveralls"
          otp_release: 21.2
          elixir: 1.6.6
          env: PRESET=test_with_coveralls

cache:
    directories:
        - .dialyzer
